apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcls-fel-surrogate-deployment
  namespace: lume-online-ml
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lcls-fel-surrogate
  template:
    metadata:
      labels:
        app: lcls-fel-surrogate
      annotations:
        configmap/version: "v2"
    spec:
      containers:
      - name: lcls-fel-surrogate
        image: ghcr.io/slaclab/lcls-fel-surrogate:99ac25d
        imagePullPolicy: Always
        restartPolicy: Always
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
          - name: EPICS_CA_ADDR_LIST
            valueFrom:
              secretKeyRef:
                name: epics-secrets
                key: ca_addr_list
          - name: K2EG_PYTHON_CONFIGURATION_PATH_FOLDER
            value: /app/src/config
          - name: MODEL_VERSION
            value: "1"
        volumeMounts:
          - name: s3cmd-config-volume
            mountPath: /app/src/config/lcls.ini
            subPath: lcls.ini
      volumes:
        - name: s3cmd-config-volume
          configMap:
            name: k2eg-config-map-fel
